/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "ssl_gc_game_event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GameEvent, GameEvent, AUTO)


PB_BIND(GameEvent_BallLeftField, GameEvent_BallLeftField, AUTO)


PB_BIND(GameEvent_AimlessKick, GameEvent_AimlessKick, AUTO)


PB_BIND(GameEvent_Goal, GameEvent_Goal, AUTO)


PB_BIND(GameEvent_IndirectGoal, GameEvent_IndirectGoal, AUTO)


PB_BIND(GameEvent_ChippedGoal, GameEvent_ChippedGoal, AUTO)


PB_BIND(GameEvent_BotTooFastInStop, GameEvent_BotTooFastInStop, AUTO)


PB_BIND(GameEvent_DefenderTooCloseToKickPoint, GameEvent_DefenderTooCloseToKickPoint, AUTO)


PB_BIND(GameEvent_BotCrashDrawn, GameEvent_BotCrashDrawn, AUTO)


PB_BIND(GameEvent_BotCrashUnique, GameEvent_BotCrashUnique, AUTO)


PB_BIND(GameEvent_BotPushedBot, GameEvent_BotPushedBot, AUTO)


PB_BIND(GameEvent_BotTippedOver, GameEvent_BotTippedOver, AUTO)


PB_BIND(GameEvent_DefenderInDefenseArea, GameEvent_DefenderInDefenseArea, AUTO)


PB_BIND(GameEvent_DefenderInDefenseAreaPartially, GameEvent_DefenderInDefenseAreaPartially, AUTO)


PB_BIND(GameEvent_AttackerTouchedBallInDefenseArea, GameEvent_AttackerTouchedBallInDefenseArea, AUTO)


PB_BIND(GameEvent_BotKickedBallTooFast, GameEvent_BotKickedBallTooFast, AUTO)


PB_BIND(GameEvent_BotDribbledBallTooFar, GameEvent_BotDribbledBallTooFar, AUTO)


PB_BIND(GameEvent_AttackerTouchedOpponentInDefenseArea, GameEvent_AttackerTouchedOpponentInDefenseArea, AUTO)


PB_BIND(GameEvent_AttackerDoubleTouchedBall, GameEvent_AttackerDoubleTouchedBall, AUTO)


PB_BIND(GameEvent_AttackerTooCloseToDefenseArea, GameEvent_AttackerTooCloseToDefenseArea, AUTO)


PB_BIND(GameEvent_BotHeldBallDeliberately, GameEvent_BotHeldBallDeliberately, AUTO)


PB_BIND(GameEvent_BotInterferedPlacement, GameEvent_BotInterferedPlacement, AUTO)


PB_BIND(GameEvent_MultipleCards, GameEvent_MultipleCards, AUTO)


PB_BIND(GameEvent_MultipleFouls, GameEvent_MultipleFouls, AUTO)


PB_BIND(GameEvent_MultiplePlacementFailures, GameEvent_MultiplePlacementFailures, AUTO)


PB_BIND(GameEvent_KickTimeout, GameEvent_KickTimeout, AUTO)


PB_BIND(GameEvent_NoProgressInGame, GameEvent_NoProgressInGame, AUTO)


PB_BIND(GameEvent_PlacementFailed, GameEvent_PlacementFailed, AUTO)


PB_BIND(GameEvent_UnsportingBehaviorMinor, GameEvent_UnsportingBehaviorMinor, AUTO)


PB_BIND(GameEvent_UnsportingBehaviorMajor, GameEvent_UnsportingBehaviorMajor, AUTO)


PB_BIND(GameEvent_KeeperHeldBall, GameEvent_KeeperHeldBall, AUTO)


PB_BIND(GameEvent_PlacementSucceeded, GameEvent_PlacementSucceeded, AUTO)


PB_BIND(GameEvent_Prepared, GameEvent_Prepared, AUTO)


PB_BIND(GameEvent_BotSubstitution, GameEvent_BotSubstitution, AUTO)


PB_BIND(GameEvent_ChallengeFlag, GameEvent_ChallengeFlag, AUTO)


PB_BIND(GameEvent_EmergencyStop, GameEvent_EmergencyStop, AUTO)


PB_BIND(GameEvent_TooManyRobots, GameEvent_TooManyRobots, AUTO)


PB_BIND(GameEvent_BoundaryCrossing, GameEvent_BoundaryCrossing, AUTO)


PB_BIND(GameEvent_PenaltyKickFailed, GameEvent_PenaltyKickFailed, AUTO)




