/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "ssl_gc_referee_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Referee, Referee, 2)


PB_BIND(Referee_TeamInfo, Referee_TeamInfo, AUTO)


PB_BIND(Referee_Point, Referee_Point, AUTO)


PB_BIND(GameEventProposalGroup, GameEventProposalGroup, AUTO)





