/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "ssl_gc_geometry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Vector2, Vector2, AUTO)


PB_BIND(Vector3, Vector3, AUTO)



